"""Argus -- re-serializes models/pattern_analyst*.joblib under whatever
xgboost version is ACTUALLY installed in the environment this is run from.

Why this exists: pickling an XGBClassifier directly (not via
Booster.save_model()'s native json/ubj format) embeds a version tag, and
loading it with a different xgboost version prints a "configuration
generated by an older version of XGBoost" warning -- harmless to
predictions, but it looks like a real failure and is worth silencing by
matching the file to the environment that actually runs it.

This has now happened twice in this project across three different
Python environments (a cloud sandbox venv, a sandboxed dev-machine bridge
shell, and the real native Anaconda environment) that all report
different installed xgboost versions -- so re-run this script, in
whichever environment you'll actually demo/submit from, any time the
warning reappears after a `pip install`/`conda install` touches xgboost.

Does NOT retrain anything. Verifies bit-identical predictions before and
after re-saving via a deterministic fingerprint (zero row, all-ones row,
a linspace row) so this is provably a pure re-serialization, not a
silent model change.

Run: PYTHONPATH=. python scripts/fix_model_pickle_version.py
"""
import warnings

import joblib
import numpy as np
import xgboost

MODEL_PATHS = [
    "models/pattern_analyst.joblib",
    "models/pattern_analyst_hardened.joblib",
]


def fingerprint(model, n_features):
    rows = np.vstack([np.zeros(n_features), np.ones(n_features), np.linspace(0, 1, n_features)])
    return model.predict_proba(rows)[:, 1].round(8).tolist()


def main():
    print(f"Installed xgboost: {xgboost.__version__}\n")
    for path in MODEL_PATHS:
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter("always")
            bundle = joblib.load(path)
            had_warning = any("older version of XGBoost" in str(x.message) for x in w)
        model = bundle["model"] if isinstance(bundle, dict) else bundle
        fp_before = fingerprint(model, model.n_features_in_)
        print(f"{path}")
        print(f"  version-skew warning before: {had_warning}")

        if not had_warning:
            print("  already matches this environment's xgboost version -- skipping re-save.\n")
            continue

        joblib.dump(bundle, path)

        with warnings.catch_warnings(record=True) as w2:
            warnings.simplefilter("always")
            bundle2 = joblib.load(path)
            had_warning2 = any("older version of XGBoost" in str(x.message) for x in w2)
        model2 = bundle2["model"] if isinstance(bundle2, dict) else bundle2
        fp_after = fingerprint(model2, model2.n_features_in_)

        print(f"  re-saved under xgboost {xgboost.__version__}")
        print(f"  version-skew warning after: {had_warning2}")
        print(f"  predictions bit-identical before/after: {fp_before == fp_after}\n")
        if fp_before != fp_after:
            print("  !! MISMATCH -- do not commit this, something is wrong. Investigate before proceeding.\n")


if __name__ == "__main__":
    main()
